-- AlterTable
ALTER TABLE `debt` ADD COLUMN `status` ENUM('CONFIRMED', 'CANCELED') NOT NULL DEFAULT 'CONFIRMED';

-- AlterTable
ALTER TABLE `expense` ADD COLUMN `status` ENUM('CONFIRMED', 'CANCELED') NOT NULL DEFAULT 'CONFIRMED';

-- CreateTable
CREATE TABLE `Payment` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `debtId` INTEGER NOT NULL,
    `amount` DECIMAL(10, 2) NOT NULL,
    `paymentDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `paymentMethod` VARCHAR(191) NOT NULL,
    `status` ENUM('CONFIRMED', 'CANCELED') NOT NULL DEFAULT 'CONFIRMED',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,
    `createdById` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Payment` ADD CONSTRAINT `Payment_debtId_fkey` FOREIGN KEY (`debtId`) REFERENCES `Debt`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
